[package]
name = "bareclad"
version = "0.1.1"
edition = "2021"
authors = ["Lars Rönnbäck <lars@bareclad.com>"]

[dependencies]
chrono = "0.4"
bimap = "0.6.1"
typemap = "0.3.3"
text_io = "0.1.9"
#jql = "3.0.4"
#serde = "1.0.130"
#serde_json = "1.0.72"
#chumsky = "0.7"
logos = "0.12"
config = "0.11"
fancy-regex = "0.7.1"
rusqlite = { version = "0.26.3", features = ["chrono", "serde_json", "bundled"] }

